version: '3'

services:
  django:
    build: /backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - /backend/.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "testdb", "-h", "localhost", "-p", "5432", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"