version: '3'

services:
  django:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "testdb", "-h", "localhost", "-p", "5432", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"

  redis:
    image: redis:latest
    depends_on:
      - django

  worker:
    build: ./backend
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - django
      - postgres

  worker-beat:
    build: ./backend
    hostname: worker-beat
    entrypoint: celery
    command: -A celery_app.app beat --loglevel=info
    depends_on:
      - redis
      - django
      - postgres

  flower:
    build: ./backend
    entrypoint: celery
    command: -A celery_app.app flower --loglevel=info
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"