# Generated by Django 5.0.1 on 2024-04-09 16:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_vector_trigger'),
        ('users', '0006_unregistereduser_contact_person_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=36, null=True)),
                ('status', models.CharField(choices=[('in_process', 'В обробці'), ('waiting_for_payment', 'Очікує оплати'), ('payed', 'Оплачено'), ('waiting_for_sending', 'Готується до відправки'), ('sent', 'Відправлено'), ('received', 'Отримано'), ('cancelled', 'Скасовано'), ('returned', 'Повернено')], max_length=22)),
                ('payment_type', models.CharField(choices=[('on_post', 'При отриманні на пошті'), ('online', 'Онлайн-оплата')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unregistered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.unregistereduser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Quantity must be greater than or equal to 1.')])),
                ('changeable_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.changeableprice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderItem', to='products.product'),
        ),
    ]
