# Generated by Django 5.0.1 on 2024-01-27 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_initial_custom_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'brands',
                'verbose_name_plural': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sale', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Sale cannot be negative.'), django.core.validators.MaxValueValidator(100, message='Sale cannot be greater than 100.')])),
                ('is_new', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Quantity cannot be negative')])),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.brand')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory')),
                ('weight', models.DecimalField(blank=False, decimal_places=2, max_digits=7, null=False, default=1)),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'product',
            },
        ),
        migrations.CreateModel(
            name='ChangeablePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sale', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Sale cannot be negative.'), django.core.validators.MaxValueValidator(100, message='Sale cannot be greater than 100.')])),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changeable_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'changeable prices',
                'verbose_name_plural': 'changeable price',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('order', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'product images',
                'verbose_name_plural': 'product image',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='products.product')),
            ],
            options={
                'verbose_name': 'tags',
                'verbose_name_plural': 'tag',
            },
        ),
    ]
