# Generated by Django 5.0.1 on 2024-02-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeableprice',
            old_name='sale',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='changeableprice',
            name='quantity_in_pack',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdditionalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to='products.product')),
            ],
            options={
                'verbose_name': 'additional field',
                'verbose_name_plural': 'additional fields',
            },
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
