# Generated by Django 5.0.1 on 2024-03-08 16:41

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_initial_custom_data'),
        ('products', '0004_initial_custom_product_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='products_pr_search__98d711_gin'),
        ),
    ]
