const actions = {
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  FETCH_PRODUCT_ADDITIONAL_DATA_REQUEST: 'FETCH_PRODUCT_ADDITIONAL_DATA_REQUEST',
  FETCH_PRODUCT_ADDITIONAL_DATA_SUCCESS: 'FETCH_PRODUCT_ADDITIONAL_DATA_SUCCESS',
  FETCH_PRODUCT_ADDITIONAL_DATA_FAILURE: 'FETCH_PRODUCT_ADDITIONAL_DATA_FAILURE',
  FETCH_PRODUCT_ADDITIONAL_DATA_ID_REQUEST: 'FETCH_PRODUCT_ADDITIONAL_DATA_ID_REQUEST',
  FETCH_PRODUCT_ADDITIONAL_DATA_ID_SUCCESS: 'FETCH_PRODUCT_ADDITIONAL_DATA_ID_SUCCESS',
  FETCH_PRODUCT_ADDITIONAL_DATA_ID_FAILURE: 'FETCH_PRODUCT_ADDITIONAL_DATA_ID_FAILURE',
  FETCH_PRODUCT_CHANGEABLE_PRICES_REQUEST: 'FETCH_PRODUCT_CHANGEABLE_PRICES_REQUEST',
  FETCH_PRODUCT_CHANGEABLE_PRICES_SUCCESS: 'FETCH_PRODUCT_CHANGEABLE_PRICES_SUCCESS',
  FETCH_PRODUCT_CHANGEABLE_PRICES_FAILURE: 'FETCH_PRODUCT_CHANGEABLE_PRICES_FAILURE',
  FETCH_PRODUCT_CHANGEABLE_PRICES_ID_REQUEST: 'FETCH_PRODUCT_CHANGEABLE_PRICES_ID_REQUEST',
  FETCH_PRODUCT_CHANGEABLE_PRICES_ID_SUCCESS: 'FETCH_PRODUCT_CHANGEABLE_PRICES_ID_SUCCESS',
  FETCH_PRODUCT_CHANGEABLE_PRICES_ID_FAILURE: 'FETCH_PRODUCT_CHANGEABLE_PRICES_ID_FAILURE',
  FETCH_PRODUCT_ID_REQUEST: 'FETCH_PRODUCT_ID_REQUEST',
  FETCH_PRODUCT_ID_SUCCESS: 'FETCH_PRODUCT_ID_SUCCESS',
  FETCH_PRODUCT_ID_FAILURE: 'FETCH_PRODUCT_ID_FAILURE',
};

export default actions;
