# Generated by Django 5.0.1 on 2024-01-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalcategory',
            options={'verbose_name': 'animal category', 'verbose_name_plural': 'animal categories'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'product category', 'verbose_name_plural': 'product categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='animal_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='categories.animalcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.productcategory'),
        ),
    ]
