# Generated by Django 5.0.1 on 2024-02-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_animalcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalcategory',
            name='key',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
