const actions = {
  FETCH_SUB_CATEGORIES_REQUEST: 'FETCH_SUB_CATEGORIES_REQUEST',
  FETCH_SUB_CATEGORIES_SUCCESS: 'FETCH_SUB_CATEGORIES_SUCCESS',
  FETCH_SUB_CATEGORIES_FAILURE: 'FETCH_SUB_CATEGORIES_FAILURE',
  FETCH_SUB_CATEGORY_ID_REQUEST: 'FETCH_SUB_CATEGORY_ID_REQUEST',
  FETCH_SUB_CATEGORY_ID_SUCCESS: 'FETCH_SUB_CATEGORY_ID_SUCCESS',
  FETCH_SUB_CATEGORY_ID_FAILURE: 'FETCH_SUB_CATEGORY_ID_FAILURE',
};

export default actions;
