# Generated by Django 5.0.1 on 2024-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='hash_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='featuredproducts',
            name='hash_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
