# Generated by Django 5.0.1 on 2024-03-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_cart_hash_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashCode',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key'))]
        ),
        migrations.AlterField(
            model_name='cart',
            name='hash_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='users.hashcode'),
        ),
        migrations.AlterField(
            model_name='featuredproducts',
            name='hash_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='users.hashcode'),
        ),
    ]
