# Generated by Django 5.0.1 on 2024-03-27 12:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_vector_trigger'),
        ('users', '0003_hashcode_alter_cart_hash_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='changeable_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.changeableprice'),
        ),
        migrations.AddField(
            model_name='featureditem',
            name='changeable_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.changeableprice'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Quantity must be greater than or equal to 1.')]),
        ),
    ]
