# Generated by Django 5.0.1 on 2024-04-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cartitem_changeable_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='featuredproducts',
            name='hash_code',
        ),
        migrations.AddField(
            model_name='user',
            name='counterparty_ref',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='UnregisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('second_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('counterparty_ref', models.CharField(blank=True, max_length=36, null=True)),
                ('hash_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.hashcode')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='unregistered_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.unregistereduser'),
        ),
        migrations.AddField(
            model_name='featuredproducts',
            name='unregistered_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='users.unregistereduser'),
        ),
    ]
