# Generated by Django 5.0.1 on 2024-04-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_cart_hash_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregistereduser',
            name='contact_person_ref',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person_ref',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
