const actions = {
  FETCH_PRODUCT_CATEGORIES_REQUEST: 'FETCH_PRODUCT_CATEGORIES_REQUEST',
  FETCH_PRODUCT_CATEGORIES_SUCCESS: 'FETCH_PRODUCT_CATEGORIES_SUCCESS',
  FETCH_PRODUCT_CATEGORIES_FAILURE: 'FETCH_PRODUCT_CATEGORIES_FAILURE',
  FETCH_PRODUCT_CATEGORY_ID_REQUEST: 'FETCH_PRODUCT_CATEGORY_ID_REQUEST',
  FETCH_PRODUCT_CATEGORY_ID_SUCCESS: 'FETCH_PRODUCT_CATEGORY_ID_SUCCESS',
  FETCH_PRODUCT_CATEGORY_ID_FAILURE: 'FETCH_PRODUCT_CATEGORY_ID_FAILURE',
};

export default actions;
